# Generated by Django 6.0.3 on 2026-06-21 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Running', max_length=20)),
                ('overall_threat_level', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('full_report_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('risk_level', models.CharField(max_length=50)),
                ('affected_path', models.TextField()),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.scan')),
            ],
        ),
    ]
